// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Simple_Bank_Teller.Models;

public partial class Account
{
    public long Id { get; set; }

    public long AccountInformationId { get; set; }

    public long? AccountNo { get; set; }

    public int? AccountType { get; set; }

    public string? UserName { get; set; }

    public string? Password { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? Timestamp { get; set; }
}