// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Simple_Bank_Teller.Models;

public partial class AccountInformation
{
    public long Id { get; set; }

    public string? FirstName { get; set; }

    public string? MiddleName { get; set; }

    public string? LastName { get; set; }

    public int? Gender { get; set; }

    public string? ContactNo { get; set; }

    public string? Address { get; set; }

    public string? EmailAddress { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? Timestamp { get; set; }
}