// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Simple_Bank_Teller.Models;

public partial class MembershipType
{
    public int Id { get; set; }

    public string? Type { get; set; }

    public string? HardCode { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? Timestamp { get; set; }
}